pipeline {
    agent any

    stages {
        stage('Initialize') {
            steps {
                echo 'Initializing CI/CD Pipeline'
    ***REMOVED***
***REMOVED***

        stage('Stop Old Backend') {
            steps {
      ***REMOVED*****REMOVED*****REMOVED***
                            sh 'fuser -k -n tcp 8088'
 ***REMOVED*****REMOVED*****REMOVED*****REMOVED*** catch (err) {
                            echo err.getMessage()
 ***REMOVED*****REMOVED*****REMOVED*****REMOVED***
    ***REMOVED***
***REMOVED***

        stage('Deploy New Backend') {
            steps {
                sh 'mvn clean package -Dmaven.test.skip=true'
                sh 'mv -f /root/.jenkins/workspace/photoly/api/target/photoly.war /home/ubuntu/photoly_b/photoly.war'
                sh 'chmod 777 /home/ubuntu/photoly_b/photoly.war'
                sh 'nohup java -jar /home/ubuntu/photoly_b/photoly.war > /home/ubuntu/photoly_b/photoly.log &'
    ***REMOVED***
***REMOVED***

        stage('Finish') {
            steps {
                echo 'Finished. Done.'
    ***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***