pipeline {
    agent any

    stages {
        stage('Initialize') {
            steps {
                echo 'Initializing CI/CD Pipeline'
            }
        }

        stage('Stop Old Backend') {
            steps {
                        try {
                            sh 'fuser -k -n tcp 8088'
                        } catch (err) {
                            echo err.getMessage()
                        }
            }
        }

        stage('Deploy New Backend') {
            steps {
                sh 'mvn clean package -Dmaven.test.skip=true'
                sh 'mv -f /root/.jenkins/workspace/photoly/api/target/photoly.war /home/ubuntu/photoly_b/photoly.war'
                sh 'chmod 777 /home/ubuntu/photoly_b/photoly.war'
                sh 'nohup java -jar /home/ubuntu/photoly_b/photoly.war > /home/ubuntu/photoly_b/photoly.log &'
            }
        }

        stage('Finish') {
            steps {
                echo 'Finished. Done.'
            }
        }
    }
}